<?php ?>
<?php
$value = $block->getCronExpr() ?: '0 0 1 * *';
?>
<div id="au_cron_expr"></div>
<input id="au_cron_expr_value"
       value="<?php echo $value ?>"
       type="hidden"
       class="input-text admin__control-text"
       name="groups[payments_section][groups][payments_au][fields][cron_expr][value]" />

<script>
    require([
        'jquery',
        'cronExprGen'
    ], function($) {
        $('#au_cron_expr').cron({
            initial: '<?php echo $value ?>',
            onChange: function() {
                $('#au_cron_expr_value').val($(this).cron('value'));
            }
        });
    });
</script>
