<?php

// @codingStandardsIgnoreFile

/** @var \Magento\Payment\Block\Transparent\Iframe $block */
$params = $block->getParams();
?>
var require = window.top.require;
require(
    [
        'jquery',
        'Magento_Checkout/js/model/quote',
        'Magento_Checkout/js/action/place-order',
        'Magento_Checkout/js/action/redirect-on-success',
        'Magento_Checkout/js/model/full-screen-loader',
        'Payments_ThreeDSecure/js/view/payment/cardinal'
    ],
    function ($, quote, placeOrderAction, redirectOnSuccessAction, fullScreenLoader, Cardinal) {
        var parent = window.top;

        <?php if (isset($params['email'])): ?>
        quote.guestEmail = '<?php echo $params['email'] ?>';
        <?php endif; ?>

        <?php if ($params['3ds_active'] ?? false): ?>
        Cardinal.init(false);
        <?php endif; ?>

        $(parent).trigger('clearTimeout');
        $.when(
            <?php if ($params['3ds_active'] ?? false): ?>
            Cardinal.setup(),
            <?php endif; ?>
            placeOrderAction(<?php echo json_encode($params['payload'] ?? []) ?>)
        ).done(
            function () {
                redirectOnSuccessAction.execute();
            }
        ).fail(
            function () {
                var parent = window.top;
                $(parent).trigger('clearTimeout');
                fullScreenLoader.stopLoader();
            }
        );
    }
);
