<?php

// @codingStandardsIgnoreFile
/**
 * @var \Payments\PayPal\Block\Express\Form $block
 */
$code = $block->escapeHtml($block->getBillingAgreementCode());
?>
<fieldset class="fieldset paypal items redirect" style="display:none;"
          id="payment_form_<?php echo $block->escapeHtml($block->getMethodCode()) ?>">
    <div><?php echo $block->escapeHtml($block->getRedirectMessage()) ?></div>
</fieldset>
